# frozen_string_literal: true

source "https://rubygems.org"

gem 'allure-cucumber', '~> 2.14', '>= 2.14.5'
gem "cucumber", "5.2"
gem "capybara", "3.33"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.10"
gem "faker", "2.14"
gem "pry", "~> 0.14.1"
gem "site_prism", ">= 3.7.1"
gem "cpf_faker" 